# Generated by Django 4.1.7 on 2023-07-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payApp', '0002_user_order_id_user_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
